resources:
- ../standalone_negs_glb_a
- ../standalone_negs_glb_b
#- ../standalone_negs_ilb_a
#- ../standalone_negs_ilb_b


configMapGenerator:
- name: standalone-negs-backend-cm
  envs: [environment.properties]

vars:
- name: PROJECT_ID
  objref:
    kind: ConfigMap
    name: standalone-negs-backend-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.PROJECT_ID
- name: GLB_BACKEND_SERVICE_A
  objref:
    kind: ConfigMap
    name: standalone-negs-backend-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.GLB_BACKEND_SERVICE_A
- name: GLB_BACKEND_SERVICE_B
  objref:
    kind: ConfigMap
    name: standalone-negs-backend-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.GLB_BACKEND_SERVICE_B
- name: ILB_REGION
  objref:
    kind: ConfigMap
    name: standalone-negs-backend-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.ILB_REGION
- name: ILB_BACKEND_SERVICE_A
  objref:
    kind: ConfigMap
    name: standalone-negs-backend-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.ILB_BACKEND_SERVICE_A
- name: ILB_BACKEND_SERVICE_B
  objref:
    kind: ConfigMap
    name: standalone-negs-backend-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.ILB_BACKEND_SERVICE_B