stages:
- docker_build
- docker_push

build image:
  stage: docker_build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_SHA

push image:
  stage: docker_push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  needs:
  - "build image"
  variables:
    GIT_STRATEGY: none
    VERSION: 2.0.0
    OS: linux
    ARCH: amd64
  script:
    - mkdir -p /usr/local/bin
    - wget "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" -O-| tar xz --to-stdout ./docker-credential-gcr > /usr/local/bin/docker-credential-gcr
    - chmod +x /usr/local/bin/docker-credential-gcr
    - /usr/local/bin/docker-credential-gcr configure-docker
    - VERSION=$(cat version.txt)
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane cp $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_SHA gcr.io/jkwng-images/helloweb:$CI_COMMIT_SHA
    - crane cp $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_SHA gcr.io/jkwng-images/helloweb:$VERSION
    - crane cp $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_SHA gcr.io/jkwng-images/helloweb:latest