apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
  annotations:
    iam.gke.io/gcp-service-account: custom-metrics@jkwng-helloweb-dev-2a11.iam.gserviceaccount.com