apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloweb-route-external
  namespace: helloweb
spec:
  # forward traffic to the gateway to the helloweb service
  hosts:
  - 'helloweb.gcp.jkwong.info'
  gateways:
  - helloweb-gateway
  http:
  - name: helloweb
    route:
    - destination:
        host: helloweb.helloweb.svc.cluster.local
