apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-service-glb
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - external:
      metric:
       name: loadbalancing.googleapis.com|https|backend_request_count
       selector:
         matchLabels:
           resource.labels.backend_target_name: helloweb-2a11-27ce-a
      target:
        type: AverageValue
        averageValue: 5000m
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloweb
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
