apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-service-glb
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
       name: requests_total
      target:
        type: AverageValue
        averageValue: 25000m
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloweb
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
