apiVersion: v1
kind: Service
metadata:
  annotations:
    controller.autoneg.dev/neg: '{"backend_services":{"8080":[{"name":"$(GLB_BACKEND_SERVICE_A)","max_rate_per_endpoint":10}]}}'
  name: helloweb
