apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-grpc
  name: helloworld-grpc
spec:
  selector:
    matchLabels:
      app: helloworld-grpc
  template:
    metadata:
      labels:
        app: helloworld-grpc
    spec:
      containers:
      - image: helloworld-grpc:latest
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 50051
          protocol: TCP
          name: grpc
