

resources:
- https://raw.githubusercontent.com/GoogleCloudPlatform/gke-autoneg-controller/v0.9.6/deploy/autoneg.yaml
- serviceaccount.yaml
# for some reason, kustomize could not patch rolebindings, so creating a second one with correct subject
- rolebinding.yaml

patchesStrategicMerge:
- deployment-sa.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: autoneg-manager-rolebinding
  path: rolebinding-subject.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: autoneg-proxy-rolebinding
  path: rolebinding-subject.yaml

namespace: autoneg-system