apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: autoneg
  name: autoneg-leader-election-rolebinding2
  namespace: autoneg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autoneg-leader-election-role
subjects:
- kind: ServiceAccount
  name: autoneg
  namespace: autoneg-system