apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloweb
  name: helloweb-ilb
  annotations:
    controller.autoneg.dev/neg: '{"backend_services":{"8080":[{"name":"$(ILB_BACKEND_SERVICE_A)","region":"$(ILB_REGION)","max_rate_per_endpoint":1}]}}'
    cloud.google.com/neg: '{"exposed_ports": {"8080":{}}}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: helloweb
