name: 'build and push image'

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/801352177098/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions'
        service_account: 'github-actions@jkwng-gitlab.iam.gserviceaccount.com'

    - id: 'setup-gcloud'
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 363.0.0'

    - id: 'setup-docker-buildx'
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - id: 'configure-docker'
      name: Configure docker
      run: 'gcloud auth configure-docker'

    - id: 'image-version'
      run: |
        echo "image_tag=$(cat version.txt)" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gcr.io/jkwng-images/helloweb:${{ env.image_tag }}